services:
  - type: web
    name: esperanto-telegram-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run bot
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBAPP_URL
        value: https://esperanto-leto-miniapp.onrender.com
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false

  - type: static
    name: esperanto-leto-miniapp
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    autoDeploy: true
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
