services:
  - type: web
    name: esperanto-telegram-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run bot
    envVars:
      - key: BOT_TOKEN
        value: your-real-bot-token
      - key: SUPABASE_URL
        value: https://your.supabase.co
      - key: SUPABASE_KEY
        value: your-supabase-service-key
      - key: OPENAI_API_KEY
        value: sk-...
    autoDeploy: true
